# Generated by Django 3.2.4 on 2021-06-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0004_alter_item_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
    ]
