# Generated by Django 3.2.4 on 2021-07-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0006_item_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
